server :
  port : 9002
kafka:
  consumer:
    bootstrap-servers: "localhost:9092"
    topic: "test_topic"
    keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
    valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde


